name: Add issues w/o project to project TR Current

on:
  issues:
    types: [opened]
  
jobs:
  add-to-project:
    name: Add issue to project TR Current
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.5.0
        with:
          project-url: https://github.com/orgs/thinkingrock-gtd/projects/2
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
